name: Go

on:
  push:
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      URL_DEPLOY: ${{ secrets.URL_DEPLOY }}
    steps:
      - uses: actions/checkout@v3
      - name: WEB
        run: curl -X POST $URL_DEPLOY
